### ISSUE TITLE
Version 0.2.0a0 - push to main

### ISSUE THREAD

**Issue by kobebryant432** [CORDEX-be2/ValEnsPy#148]
I propose preparing Version 0.1.1. 
This will be a first version which users could use without being a developer. 
All basic components should be included.

Steps before this can be done: 

- [ ] Clean up and organize example notebooks
- [ ] Documentation - update
- [x] #127 
- [ ] 

Feel free to add todos and/or add the v0.1.1 milestone to issue that we feel are essential for a clean version.

**Comment by kobebryant432** [comment]
🍾 🍾 🍾 
There is now a (tested) working version on PyPi which we can easily update with new releases!
https://pypi.org/project/ValEnsPy/

**Comment by Ivanderkelen** [comment]
Congratulations Kobe! Great way to start the long weekend! 🥳
