### ISSUE TITLE
Going public! 

### ISSUE THREAD

**Issue by Ivanderkelen** [CORDEX-be2/ValEnsPy#162]
Things to consider before going public with Valenspy: 
following meeting with @kobebryant432 and @bertvs1 on 25/9, feel free to add on 

- [x] Paths with data on HPC: is it a problem to include them? (At first sight not immedeately a problem, but to think about)
- [x] Publication of evaluation figures with model (test) runs: problem when accessible to everyone (but who is going to find and use them anyway?)
- [x] we need to [choose a license](https://choosealicense.com/)
- [x] Investigate possibility of private branches within public repository

**Comment by kobebryant432** [comment]
The package is now public!
